version: '3'

services:
  rabbitmq:
    image: rabbitmq:3.10.7-management
    hostname: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASSWORD=guest
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,error},{default,error}] disk_free_limit 2147483648
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"

  order-service:
    build:
      context: "./order-service"
    restart: always
    ports:
      - "8083:80"

  delivery-service:
    build:
      context: "./delivery-service"
    restart: always

  notification-service:
    build:
      context: "./notification-service"
    restart: always